require 'itunes-client'

module MorningMusic
  include Itunes

  @tracks = []
  @playlist = []
  @current_track ||= nil
  @prev_track ||= nil
  @power_on ||= true
  @playing ||= false

  def self.power_on
    @power_on
  end

  def self.playing?
    @playing
  end

  def self.create
    Dir.chdir("./music") # Sets working directory to music folder
    Dir.glob("*mp3") { |track| @tracks << "#{track}"} # Parse music folder to get all mp3 files
    Dir.glob("*m4a") { |track| @tracks << "#{track}"} # Parse music folder to get all mp3 files
  end

  def self.seed_playlist
    @tracks.each { |track| @playlist << Itunes::Player.add(track)} # Populates the playlist with extracted music files.
    @playlist.compact!.uniq # No idea why, but there are two random nils that gets generated by this gem
  end

  def self.current_track
    @current_track
  end

  def self.current_track=(track)
    @current_track = track
  end

  def self.set_current_track
    @current_track = @playlist.shuffle.pop
  end

  def self.play
    if self.playing?
      puts "Track is already playing!"
      puts
    else
      @current_track.play
      @playing = true
    end
  end

  def self.stop
    @current_track.stop
    @playing = false
  end

  def self.next
    @prev_track = @current_track
    @current_track = self.set_current_track
    @playing = false
    self.play
  end

  def self.prev
    puts "There are no previous tracks!" if @prev_track.nil?
    @current_track = @prev_track
    @current_track.play
  end

  def self.exit
    MorningMusic.stop
    @power_on = false
  end
end